#!/bin/bash
#
# Simplified OpenClaw Security Report Generator
# Version: 1.1
#

set -e

# Configuration
REPORT_DIR="/tmp/openclaw-reports"
mkdir -p "$REPORT_DIR"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${BLUE}=== OpenClaw Security Report Generator ===${NC}"
echo ""

# Generate JSON report
echo "📄 Generating JSON report..."
cat > "$REPORT_DIR/security-report-$TIMESTAMP.json" << EOF
{
  "report": {
    "version": "1.0",
    "generated_at": "$(date -Iseconds)",
    "tool": "openclaw-healthcheck",
    "host": "$(hostname)",
    "os": "$(uname -s)"
  },
  "summary": {
    "status": "test",
    "findings": 0
  }
}
EOF
echo -e "   ${GREEN}✓${NC} $REPORT_DIR/security-report-$TIMESTAMP.json"

# Generate Markdown report
echo "📄 Generating Markdown report..."
cat > "$REPORT_DIR/security-report-$TIMESTAMP.md" << EOF
# OpenClaw Security Report

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')
**Tool**: openclaw-healthcheck
**Host**: $(hostname)

---

## Summary

- Status: Test Report
- Findings: 0

## Quick Commands

\`\`\`bash
# Basic audit
openclaw security audit

# Deep audit
openclaw security audit --deep

# Update check
openclaw update status
\`\`\`

---
*Generated by openclaw-healthcheck*
EOF
echo -e "   ${GREEN}✓${NC} $REPORT_DIR/security-report-$TIMESTAMP.md"

# Generate HTML report
echo "📄 Generating HTML report..."
cat > "$REPORT_DIR/security-report-$TIMESTAMP.html" << EOF
<!DOCTYPE html>
<html>
<head>
    <title>OpenClaw Security Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 800px; margin: auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        .success { color: #27ae60; font-weight: bold; }
        .info { color: #3498db; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #3498db; color: white; }
        code { background: #ecf0f1; padding: 2px 6px; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ OpenClaw Security Report</h1>
        <p><strong>Generated:</strong> $(date '+%Y-%m-%d %H:%M:%S')</p>
        <p><strong>Host:</strong> $(hostname)</p>
        <p><strong>OS:</strong> $(uname -s) $(uname -r)</p>

        <h2>Status</h2>
        <p class="success">✓ Test Report Generated Successfully</p>

        <h2>Quick Commands</h2>
        <table>
            <tr><th>Command</th><th>Description</th></tr>
            <tr><td><code>openclaw security audit</code></td><td>Basic security audit</td></tr>
            <tr><td><code>openclaw security audit --deep</code></td><td>Deep security scan</td></tr>
            <tr><td><code>openclaw update status</code></td><td>Check for updates</td></tr>
        </table>
    </div>
</body>
</html>
EOF
echo -e "   ${GREEN}✓${NC} $REPORT_DIR/security-report-$TIMESTAMP.html"

echo ""
echo -e "${GREEN}=== Report Generation Complete ===${NC}"
echo ""
echo "📁 Reports saved to: $REPORT_DIR"
echo ""
ls -lh "$REPORT_DIR"/security-report-$TIMESTAMP.*
echo ""
echo "💡 To view HTML report:"
echo "   firefox $REPORT_DIR/security-report-$TIMESTAMP.html"
echo "   cat $REPORT_DIR/security-report-$TIMESTAMP.md"
echo "   cat $REPORT_DIR/security-report-$TIMESTAMP.json"
