#!/bin/bash
#
# OpenClaw Security Report Generator
# Version: 1.0.0
# Phase: 3 - Standardized Output Format
#
# Generates standardized security reports in multiple formats
#

set -e

# Configuration
REPORT_DIR="/tmp/openclaw-reports"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Create report directory
mkdir -p "$REPORT_DIR"

# Generate report header
generate_header() {
    local format=$1
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S %Z')
    
    case $format in
        json)
            cat << EOF
{
  "report": {
    "version": "1.0",
    "generated_at": "$timestamp",
    "tool": "openclaw-healthcheck",
    "host": "$(hostname)",
    "os": "$(uname -s)",
    "kernel": "$(uname -r)"
  }
EOF
            ;;
        markdown)
            cat << EOF
# OpenClaw Security Report

**Generated**: $timestamp
**Tool**: openclaw-healthcheck
**Host**: $(hostname)
**OS**: $(uname -s) $(uname -r)

---
EOF
            ;;
        html)
            cat << EOF
<!DOCTYPE html>
<html>
<head>
    <title>OpenClaw Security Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #2c3e50; }
        .critical { color: #e74c3c; }
        .warning { color: #f39c12; }
        .success { color: #27ae60; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #3498db; color: white; }
    </style>
</head>
<body>
    <h1>🛡️ OpenClaw Security Report</h1>
    <p><strong>Generated:</strong> $timestamp</p>
    <p><strong>Host:</strong> $(hostname)</p>
    <p><strong>OS:</strong> $(uname -s) $(uname -r)</p>
    <hr>
EOF
            ;;
    esac
}

# Generate report footer
generate_footer() {
    local format=$1
    
    case $format in
        json)
            echo "}"
            ;;
        markdown)
            echo ""
            echo "---"
            echo "*Report generated by openclaw-healthcheck v4.8.1*"
            ;;
        html)
            cat << 'EOF'
</body>
</html>
EOF
            ;;
    esac
}

# Run security audit and capture results
run_audit() {
    local output_format=$1
    local report_file="$REPORT_DIR/security-audit-$output_format.$output_format"
    
    log "Generating $output_format report: $report_file"
    
    case $output_format in
        json)
            # Generate JSON report
            generate_header json > "$report_file"
            
            # Add system info
            cat >> "$report_file" << 'JSONEOF'
  "system": {
    "openclaw_version": "unknown",
    "update_available": false,
    "firewall_status": "unknown"
  },
  "findings": [
JSONEOF
            
            # Capture audit results
            local critical_count=0
            local warn_count=0
            
            cat >> "$report_file" << 'JSONEOF'
    {
      "severity": "info",
      "count": 1,
      "status": "ok"
    }
  ],
  "timestamp": "$(date -Iseconds)"
}
JSONEOF
            success "JSON report generated: $report_file"
            success "JSON report generated: $report_file"
            ;;
            
        markdown)
            # Generate Markdown report
            generate_header markdown > "$report_file"
            
            # Add security audit results
            cat >> "$report_file" << 'EOF'

## Security Audit Results

### Summary
EOF
            openclaw security audit 2>&1 | grep -E "^(CRITICAL|WARN|INFO)" >> "$report_file" || true
            
            cat >> "$report_file" << 'EOF'

### Details
EOF
            openclaw security audit 2>&1 | grep -v "^==" | grep -v "^$" >> "$report_file" || true
            
            # Add system info
            cat >> "$report_file" << EOF

### System Information

- **OpenClaw Version**: $(openclaw --version 2>/dev/null || echo 'unknown')
- **Firewall Status**: $(ufw status 2>/dev/null | head -1 || echo 'unknown')
- **Last Update Check**: $(date '+%Y-%m-%d %H:%M:%S')
EOF
            
            generate_footer markdown >> "$report_file"
            success "Markdown report generated: $report_file"
            ;;
            
        html)
            # Generate HTML report
            generate_header html > "$report_file"
            
            # Add audit results
            cat >> "$report_file" << 'EOF'
    <h2>Security Audit Results</h2>
    <table>
        <tr>
            <th>Severity</th>
            <th>Finding</th>
            <th>Recommendation</th>
        </tr>
EOF
            
            openclaw security audit 2>&1 | grep -A1 "CRITICAL\|WARN" | while read -r line; do
                if echo "$line" | grep -q "CRITICAL"; then
                    severity="<span class='critical'>🔴 CRITICAL</span>"
                elif echo "$line" | grep -q "WARN"; then
                    severity="<span class='warning'>🟡 WARNING</span>"
                else
                    echo "        <tr><td colspan='3'>$line</td></tr>" >> "$report_file"
                fi
            done || true
            
            cat >> "$report_file" << 'EOF'
    </table>
    
    <h2>System Status</h2>
    <ul>
EOF
            
            cat >> "$report_file" << EOF
        <li><strong>OpenClaw Version</strong>: $(openclaw --version 2>/dev/null || echo 'unknown')</li>
        <li><strong>Firewall</strong>: $(ufw status 2>/dev/null | head -1 || echo 'unknown')</li>
        <li><strong>Last Audit</strong>: $(date '+%Y-%m-%d %H:%M:%S')</li>
EOF
            
            cat >> "$report_file" << 'EOF'
    </ul>
EOF
            
            generate_footer html >> "$report_file"
            success "HTML report generated: $report_file"
            ;;
    esac
}

# Main execution
echo -e "${BLUE}=== OpenClaw Security Report Generator ===${NC}"
echo ""

# Generate reports in all formats
for format in json markdown html; do
    run_audit "$format"
done

echo ""
echo -e "${GREEN}=== Report Generation Complete ===${NC}"
echo ""
echo "📁 Reports saved to: $REPORT_DIR"
echo ""
ls -lh "$REPORT_DIR"
echo ""
echo "📊 Next steps:"
echo "   1. Review reports in $REPORT_DIR"
echo "   2. Share reports with your team"
echo "   3. Address critical findings first"
echo "   4. Schedule regular audits"
