#!/usr/bin/env python3
"""
Report Generator for Agent Mode
Generates structured security reports
"""

import json
from datetime import datetime
from typing import Dict, List, Optional


class ReportGenerator:
    """
    Generate security reports in multiple formats
    """
    
    def __init__(self, findings: List[Dict]):
        self.findings = findings
        self.timestamp = datetime.now().isoformat()
    
    def generate_json(self) -> str:
        """
        Generate JSON format report
        """
        report = {
            'metadata': {
                'timestamp': self.timestamp,
                'scanner_version': '4.9.0',
                'scanner_mode': 'agent'
            },
            'summary': self._calculate_summary(),
            'findings': self.findings,
            'recommendations': self._generate_recommendations()
        }
        
        return json.dumps(report, indent=2)
    
    def generate_markdown(self) -> str:
        """
        Generate Markdown format report
        """
        summary = self._calculate_summary()
        
        md = f"""# Security Scan Report

**Generated:** {self.timestamp}
**Scanner Version:** 4.9.0
**Scan Mode:** Agent (Python-based)

---

## Executive Summary

| Metric | Value |
|--------|--------|
| Total Findings | {summary['total']} |
| Critical Issues | {summary['critical']} |
| High Severity | {summary['high']} |
| Medium Severity | {summary['medium']} |
| Low Severity | {summary['low']} |
| Risk Level | {self._calculate_risk_level(summary)} |

---

## Findings by Severity

"""
        
        # Group findings by severity
        by_severity = {
            'critical': [],
            'high': [],
            'medium': [],
            'low': [],
            'info': []
        }
        
        for finding in self.findings:
            severity = finding.get('severity', 'unknown')
            if severity not in by_severity:
                severity = 'info'
            by_severity[severity].append(finding)
        
        # Critical findings
        if by_severity['critical']:
            md += "### 🔴 Critical Issues\n\n"
            for idx, finding in enumerate(by_severity['critical'], 1):
                md += self._format_finding(idx, finding)
        
        # High severity
        if by_severity['high']:
            md += "\n### 🟠 High Severity Issues\n\n"
            for idx, finding in enumerate(by_severity['high'], 1):
                md += self._format_finding(idx, finding)
        
        # Medium severity
        if by_severity['medium']:
            md += "\n### 🟡 Medium Severity Issues\n\n"
            for idx, finding in enumerate(by_severity['medium'], 1):
                md += self._format_finding(idx, finding)
        
        # Low severity
        if by_severity['low']:
            md += "\n### 🟢 Low Severity Issues\n\n"
            for idx, finding in enumerate(by_severity['low'], 1):
                md += self._format_finding(idx, finding)
        
        # Info
        if by_severity['info']:
            md += "\n### ℹ️ Informational\n\n"
            for idx, finding in enumerate(by_severity['info'], 1):
                md += self._format_finding(idx, finding)
        
        # Recommendations
        md += "\n---\n\n## 📋 Recommendations\n\n"
        recommendations = self._generate_recommendations()
        for idx, rec in enumerate(recommendations, 1):
            md += f"{idx}. {rec}\n"
        
        # Footer
        md += f"\n---\n\n*Report generated by HealthCheck v4.9.0 (Agent Mode)*"
        
        return md
    
    def _calculate_summary(self) -> Dict:
        """Calculate summary statistics"""
        return {
            'total': len(self.findings),
            'critical': len([f for f in self.findings if f.get('severity') == 'critical']),
            'high': len([f for f in self.findings if f.get('severity') == 'high']),
            'medium': len([f for f in self.findings if f.get('severity') == 'medium']),
            'low': len([f for f in self.findings if f.get('severity') == 'low'])
        }
    
    def _calculate_risk_level(self, summary: Dict) -> str:
        """Calculate overall risk level"""
        if summary['critical'] > 0:
            return "🔴 CRITICAL"
        elif summary['high'] >= 3:
            return "🟠 HIGH"
        elif summary['high'] > 0 or summary['medium'] >= 5:
            return "🟡 MEDIUM"
        elif summary['medium'] > 0:
            return "🟢 MEDIUM-LOW"
        else:
            return "✅ LOW RISK"
    
    def _format_finding(self, idx: int, finding: Dict) -> str:
        """Format a single finding"""
        severity_emoji = {
            'critical': '🔴',
            'high': '🟠',
            'medium': '🟡',
            'low': '🟢',
            'info': 'ℹ️'
        }.get(finding.get('severity', 'unknown'), '❓')
        
        return f"""
#### {idx}. {finding.get('rule_id', 'Unknown')}

**Severity:** {severity_emoji} {finding.get('severity', 'unknown').upper()}

**Description:** {finding.get('description', 'No description available')}

**Status:** {finding.get('status', 'unknown')}

**Remediation:** {finding.get('remediation', 'See rule file for details')}

---
"""
    
    def _generate_recommendations(self) -> List[str]:
        """Generate prioritized recommendations"""
        recommendations = []
        
        # Check for critical issues
        critical_count = len([f for f in self.findings if f.get('severity') == 'critical'])
        if critical_count > 0:
            recommendations.append(
                f"⚠️ **URGENT**: Address {critical_count} critical issue(s) immediately. "
                "These may allow remote code execution or privilege escalation."
            )
        
        # Check for open ports
        open_ports = [f for f in self.findings if f.get('rule_id', '').startswith('port-') and f.get('status') == 'OPEN']
        if open_ports:
            recommendations.append(
                f"Review {len(open_ports)} open port(s) and ensure they are necessary."
            )
        
        # Check for outdated packages
        outdated = [f for f in self.findings if f.get('category') == 'cve']
        if outdated:
            recommendations.append(
                f"Update {len(outdated)} package(s) with known CVE vulnerabilities."
            )
        
        # General recommendation
        if not critical_count:
            recommendations.append(
                "Enable automatic security updates to stay protected against new vulnerabilities."
            )
        
        return recommendations
    
    def save_report(self, format: str = 'markdown', output_dir: str = '/tmp') -> str:
        """
        Save report to file
        Returns file path
        """
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        
        if format == 'json':
            content = self.generate_json()
            filename = f'security-report-{timestamp}.json'
        else:
            content = self.generate_markdown()
            filename = f'security-report-{timestamp}.md'
        
        filepath = os.path.join(output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(content)
        
        return filepath


def main():
    """Test report generator"""
    # Sample findings
    sample_findings = [
        {
            'rule_id': 'port-22',
            'severity': 'info',
            'description': 'SSH port is open',
            'status': 'OPEN',
            'remediation': 'Ensure SSH is configured properly'
        },
        {
            'rule_id': 'cve-2024-3094',
            'severity': 'critical',
            'description': 'Polkit privilege escalation vulnerability',
            'status': 'VULNERABLE',
            'remediation': 'Update polkit to version 0.124+'
        }
    ]
    
    generator = ReportGenerator(sample_findings)
    
    print("=== Markdown Report ===")
    print(generator.generate_markdown())
    
    print("\n=== JSON Report ===")
    print(generator.generate_json())


if __name__ == '__main__':
    main()